<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $price
 * @property string $image
 * @property integer $product_category_id
 * @property ProductCategory $ProductCategory
 * 
 * @method string          getName()                Returns the current record's "name" value
 * @method string          getDescription()         Returns the current record's "description" value
 * @method string          getPrice()               Returns the current record's "price" value
 * @method string          getImage()               Returns the current record's "image" value
 * @method integer         getProductCategoryId()   Returns the current record's "product_category_id" value
 * @method ProductCategory getProductCategory()     Returns the current record's "ProductCategory" value
 * @method Product         setName()                Sets the current record's "name" value
 * @method Product         setDescription()         Sets the current record's "description" value
 * @method Product         setPrice()               Sets the current record's "price" value
 * @method Product         setImage()               Sets the current record's "image" value
 * @method Product         setProductCategoryId()   Sets the current record's "product_category_id" value
 * @method Product         setProductCategory()     Sets the current record's "ProductCategory" value
 * 
 * @package    simple-site
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('price', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('product_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductCategory', array(
             'local' => 'product_category_id',
             'foreign' => 'id'));
    }
}