<?php

/**
 * BaseItemCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $image
 * @property Doctrine_Collection $Item
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getImage()       Returns the current record's "image" value
 * @method Doctrine_Collection getItem()        Returns the current record's "Item" collection
 * @method ItemCategory        setName()        Sets the current record's "name" value
 * @method ItemCategory        setDescription() Sets the current record's "description" value
 * @method ItemCategory        setImage()       Sets the current record's "image" value
 * @method ItemCategory        setItem()        Sets the current record's "Item" collection
 * 
 * @package    simple-site
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item', array(
             'local' => 'id',
             'foreign' => 'item_category_id'));
    }
}