<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $image
 * @property integer $item_category_id
 * @property integer $item_type_id
 * @property ItemCategory $ItemCategory
 * @property ItemType $ItemType
 * 
 * @method string       getName()             Returns the current record's "name" value
 * @method string       getDescription()      Returns the current record's "description" value
 * @method string       getImage()            Returns the current record's "image" value
 * @method integer      getItemCategoryId()   Returns the current record's "item_category_id" value
 * @method integer      getItemTypeId()       Returns the current record's "item_type_id" value
 * @method ItemCategory getItemCategory()     Returns the current record's "ItemCategory" value
 * @method ItemType     getItemType()         Returns the current record's "ItemType" value
 * @method Item         setName()             Sets the current record's "name" value
 * @method Item         setDescription()      Sets the current record's "description" value
 * @method Item         setImage()            Sets the current record's "image" value
 * @method Item         setItemCategoryId()   Sets the current record's "item_category_id" value
 * @method Item         setItemTypeId()       Sets the current record's "item_type_id" value
 * @method Item         setItemCategory()     Sets the current record's "ItemCategory" value
 * @method Item         setItemType()         Sets the current record's "ItemType" value
 * 
 * @package    simple-site
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('item_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('item_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ItemCategory', array(
             'local' => 'item_category_id',
             'foreign' => 'id'));

        $this->hasOne('ItemType', array(
             'local' => 'item_type_id',
             'foreign' => 'id'));
    }
}