<?php

/**
 * BaseUserType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $User
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getUser() Returns the current record's "User" collection
 * @method UserType            setName() Sets the current record's "name" value
 * @method UserType            setUser() Sets the current record's "User" collection
 * 
 * @package    simple-site
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'user_type_id'));
    }
}