<?php

/**
 * ItemTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemType');
    }
}