<?php

/**
 * ProductLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductLine');
    }
}