<?php

/**
 * UserTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserType');
    }
}