<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/04 05:36:59
sfConfig::add(array(
  'mod_productcategory_enabled' => true,
  'mod_productcategory_view_class' => 'sfPHP',
));
