<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/02 02:50:18
sfConfig::add(array(
  'mod_productcategory_enabled' => true,
  'mod_productcategory_view_class' => 'sfPHP',
));
