<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/02 02:31:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=site-simple',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
