<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/05 02:40:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=romina-belleza-dev',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
