<?php
// auto-generated by sfViewConfigHandler
// date: 2011/11/18 19:51:15
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Romina Crugo', false, false);
  $response->addMeta('description', 'Estética y Spa', false, false);
  $response->addMeta('keywords', 'estetica, spa', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('main_blue.css', '', array ());
  $response->addStylesheet('jquery-ui-1.8.16.custom.css', '', array ());
  $response->addJavascript('jquery-1.6.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.16.custom.min.js', '', array ());
  $response->addJavascript('jquery.history.js', '', array ());
  $response->addJavascript('global-functions.js', '', array ());
  $response->addJavascript('jquery.floatobject.js', '', array ());


