User:
  columns:
    user_type_id: { type: integer }
    username: { type: string(255), notnull: true }
    password: { type: string(255), notnull: true }
  relations:
    UserType: { local: user_type_id, foreign: id }

UserType:
  columns:
    name: { type: string(255) }

Product:
  columns:
    product_category_id: { type: integer }
    name: { type: string(255), notnull: true }
    description_short: { type: string(500), notnull: true }
    description_long: { type: string(1000), notnull: true }
    price: { type: string(255) }
    image: { type: string(255) }
  relations:
    ProductCategory: { local: product_category_id, foreign: id }

ProductCategory:
  columns:
    name: { type: string(255), notnull: true }
    description: { type: string(500) }
    image: { type: string(255) }

Service:
  columns:
    name: { type: string(255), notnull: true }
    description: { type: string(1000), notnull: true }
    image: { type: string(255) }